// <auto-generated />
using System;
using FinDataWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinDataWebAPI.Migrations
{
    [DbContext(typeof(FinancialDataContext))]
    [Migration("20240618155630_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinDataWebAPI.Models.FinancialData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.HasKey("id");

                    b.ToTable("FinancialData");
                });

            modelBuilder.Entity("FinDataWebAPI.Models.FinancialData", b =>
                {
                    b.OwnsOne("FinDataWebAPI.Models.FinMetrics", "finMetrics", b1 =>
                        {
                            b1.Property<int>("FinancialDataid")
                                .HasColumnType("int");

                            b1.Property<double>("metric1")
                                .HasColumnType("float")
                                .HasColumnName("metric1");

                            b1.Property<int>("metric2")
                                .HasColumnType("int")
                                .HasColumnName("metric2");

                            b1.Property<double>("metric3")
                                .HasColumnType("float")
                                .HasColumnName("metric3");

                            b1.Property<int>("metric4")
                                .HasColumnType("int")
                                .HasColumnName("metric4");

                            b1.Property<double>("metric5")
                                .HasColumnType("float")
                                .HasColumnName("metric5");

                            b1.Property<int>("metric6")
                                .HasColumnType("int")
                                .HasColumnName("metric6");

                            b1.HasKey("FinancialDataid");

                            b1.ToTable("FinancialData");

                            b1.WithOwner()
                                .HasForeignKey("FinancialDataid");
                        });

                    b.Navigation("finMetrics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
