// <auto-generated />
using System;
using FinDataWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinDataWebAPI.Migrations
{
    [DbContext(typeof(FinancialDataContext))]
    [Migration("20240619182923_updatedEntitiesFinMetrics")]
    partial class updatedEntitiesFinMetrics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinDataWebAPI.Models.FinancialData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.HasKey("id");

                    b.ToTable("FinancialData");
                });

            modelBuilder.Entity("FinDataWebAPI.Models.FinMetrics", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("financialDataId")
                        .HasColumnType("int");

                    b.Property<double>("metric1")
                        .HasColumnType("float")
                        .HasColumnName("metric1");

                    b.Property<int>("metric2")
                        .HasColumnType("int")
                        .HasColumnName("metric2");

                    b.Property<double>("metric3")
                        .HasColumnType("float")
                        .HasColumnName("metric3");

                    b.Property<int>("metric4")
                        .HasColumnType("int")
                        .HasColumnName("metric4");

                    b.Property<double>("metric5")
                        .HasColumnType("float")
                        .HasColumnName("metric5");

                    b.Property<int>("metric6")
                        .HasColumnType("int")
                        .HasColumnName("metric6");

                    b.HasKey("id");

                    b.HasIndex("financialDataId");

                    b.ToTable("FinMetrics");
                });

            modelBuilder.Entity("FinDataWebAPI.Models.FinMetrics", b =>
                {
                    b.HasOne("FinDataWebAPI.Models.FinancialData", "financialData")
                        .WithMany("finMetrics")
                        .HasForeignKey("financialDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("financialData");
                });

            modelBuilder.Entity("FinDataWebAPI.Models.FinancialData", b =>
                {
                    b.Navigation("finMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
